name: di_ref
description: "A Flutter DI package with registration functionality based on references and groups.
It make able to create multiple group based trees and dispose it based on DI references. "
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
